// <auto-generated />
using System;
using CS_EFCodeFirst.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CS_EFCodeFirst.Migrations
{
    [DbContext(typeof(BlueShoppingDbContext))]
    [Migration("20230515055747_firstMigration")]
    partial class firstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CS_EFCodeFirst.Models.Category", b =>
                {
                    b.Property<int>("CatrgoryUniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CatrgoryUniqueId"), 1L, 1);

                    b.Property<int>("BasePrice")
                        .HasColumnType("int");

                    b.Property<string>("CategorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturere")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CatrgoryUniqueId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("CS_EFCodeFirst.Models.Product", b =>
                {
                    b.Property<int>("ProductUniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductUniqueId"), 1L, 1);

                    b.Property<int?>("CategoryCatrgoryUniqueId")
                        .HasColumnType("int");

                    b.Property<int>("CatrgoryUniqueId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductUniqueId");

                    b.HasIndex("CategoryCatrgoryUniqueId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("CS_EFCodeFirst.Models.Product", b =>
                {
                    b.HasOne("CS_EFCodeFirst.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryCatrgoryUniqueId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CS_EFCodeFirst.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
